/**
 * Mirrors the Velite-built content index (.velite/lessons.json, produced by
 * `npm run build` from the MDX files in ../content) into the Module table so
 * the app can query/join lessons relationally. Re-run after adding lessons.
 *
 * Also mirrors docs/curriculum/*.md's per-tier checkpoint briefs into the
 * Checkpoint table (see src/lib/curriculumDocs.ts for the parser and
 * src/lib/checkpoints.ts for the shared default rubric) — same idempotent
 * upsert pattern, so a fresh database just works with no manual step.
 */
import { db } from '../src/lib/db'
import { getAllCheckpointBriefs } from '../src/lib/curriculumDocs'
import { DEFAULT_RUBRIC_ITEMS } from '../src/lib/checkpoints'
// Generated by `velite build` (runs before this in both `npm run build` and
// docker-entrypoint.sh) — resolveJsonModule in tsconfig.json handles the type.
import lessons from '../.velite/lessons.json'

async function main() {
  for (const lesson of lessons as Array<{
    moduleId: string
    trackId: string
    tier: number
    title: string
    order: number
    estimatedHours: number
  }>) {
    await db.module.upsert({
      where: { id: lesson.moduleId },
      create: {
        id: lesson.moduleId,
        trackId: lesson.trackId,
        tier: lesson.tier,
        title: lesson.title,
        order: lesson.order,
        estimatedHours: lesson.estimatedHours,
      },
      update: {
        title: lesson.title,
        order: lesson.order,
        estimatedHours: lesson.estimatedHours,
      },
    })
  }
  console.log(`Seeded ${lessons.length} modules.`)

  const checkpoints = getAllCheckpointBriefs()
  for (const checkpoint of checkpoints) {
    await db.checkpoint.upsert({
      where: { id: checkpoint.id },
      create: {
        id: checkpoint.id,
        trackId: checkpoint.trackId,
        tier: checkpoint.tier,
        title: checkpoint.title,
        rubric: JSON.stringify(DEFAULT_RUBRIC_ITEMS),
      },
      update: {
        trackId: checkpoint.trackId,
        tier: checkpoint.tier,
        title: checkpoint.title,
      },
    })
  }
  console.log(`Seeded ${checkpoints.length} checkpoints.`)
}

main()
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
  .finally(() => db.$disconnect())
