/**
 * Mirrors the Velite-built content index (.velite/lessons.json, produced by
 * `npm run build` from the MDX files in ../content) into the Module table so
 * the app can query/join lessons relationally. Re-run after adding lessons.
 */
import { db } from '../src/lib/db'
// @ts-expect-error — generated by `velite build`; absent until the content pipeline has run once
import lessons from '../.velite/lessons.json'

async function main() {
  for (const lesson of lessons as Array<{
    moduleId: string
    trackId: string
    tier: number
    title: string
    order: number
    estimatedHours: number
  }>) {
    await db.module.upsert({
      where: { id: lesson.moduleId },
      create: {
        id: lesson.moduleId,
        trackId: lesson.trackId,
        tier: lesson.tier,
        title: lesson.title,
        order: lesson.order,
        estimatedHours: lesson.estimatedHours,
      },
      update: {
        title: lesson.title,
        order: lesson.order,
        estimatedHours: lesson.estimatedHours,
      },
    })
  }
  console.log(`Seeded ${lessons.length} modules.`)
}

main()
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
  .finally(() => db.$disconnect())
